TYPE_LAYER = "layer"
TYPE_SCROLLABLE_LAYER = "scrollable_layer"
TYPE_RECT = "rect"
TYPE_TEXT = "text"
TYPE_VBOX = "vbox"
TYPE_HBOX = "hbox"
TYPE_IMAGE = "image"

KEY_TYPE = "type"
KEY_CHILDREN = "children"
KEY_RECT = "rect"
KEY_PADDING = "padding"
KEY_MARGIN = "margin"
KEY_ID = "id"
KEY_LISTEN_EVENTS = "listen_events"
KEY_TEXT = "text"
KEY_SOURCE = "source"
KEY_SCALE_MODE = "scale_mode"
KEY_FONT = "font"
KEY_FONT_SIZE = "font_size"
KEY_COLOR = "color"
KEY_ALIGN = "align"
KEY_WRAP = "wrap"
KEY_ELLIPSIS = "ellipsis"
KEY_MARKUP = "markup"
KEY_SCROLL_Y = "scroll_y"
KEY_CONTENT_HEIGHT = "content_height"

KEY_RADIUS = "radius"
KEY_BORDER_COLOR = "border_color"
KEY_BORDER_WIDTH = "border_width"

EVENT_CLICK = "click"
EVENT_LINK_CLICK = "link_click"
EVENT_QUIT = "quit"
EVENT_SCROLL = "scroll"

EVENT_HOVER_START = "hover_start"
EVENT_HOVER_END = "hover_end"
EVENT_KEY_DOWN = "key_down"
