TYPE_LAYER = "layer"
TYPE_RECT = "rect"
TYPE_TEXT = "text"
TYPE_VBOX = "vbox"
TYPE_HBOX = "hbox"

KEY_TYPE = "type"
KEY_CHILDREN = "children"
KEY_RECT = "rect"
KEY_PADDING = "padding"
KEY_MARGIN = "margin"
KEY_ID = "id"
KEY_LISTEN_EVENTS = "listen_events"
KEY_TEXT = "text"
KEY_FONT = "font"
KEY_FONT_SIZE = "font_size"
KEY_COLOR = "color"
KEY_ALIGN = "align"
KEY_WRAP = "wrap"
KEY_ELLIPSIS = "ellipsis"
KEY_MARKUP = "markup"

EVENT_CLICK = "click"
EVENT_LINK_CLICK = "link_click"

EVENT_HOVER_START = "hover_start"
EVENT_HOVER_END = "hover_end"
EVENT_KEY_DOWN = "key_down"


